# Первая лабораторная работа

## Установка и импорт необходимых библиотек

In [10]:
!pip install pandas

Requirement already satisfied: pandas in d:\git\machinelearningutmn\.venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.22.4 in d:\git\machinelearningutmn\.venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\git\machinelearningutmn\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\git\machinelearningutmn\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\git\machinelearningutmn\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\git\machinelearningutmn\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
import pandas as pd

Загрузка набора данных и проверка корректности данных

In [12]:
df = pd.read_csv('archive/2cars_moldova.csv', delimiter = ',')
df

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Transmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,Automatic,7750.0
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,Manual,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,Manual,2200.0
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,Manual,6550.0
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,Manual,4100.0
...,...,...,...,...,...,...,...,...,...
41002,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,Manual,7000.0
41003,Renault,Modus,2009,Hatchback,225.0,1500.0,Diesel,Manual,4500.0
41004,Mercedes,E Class,2016,Sedan,50000.0,1950.0,Diesel,Automatic,29500.0
41005,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,Manual,4000.0
41006,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,Manual,4000.0

## Просмотр информации о наборе данных и предобработка

Метод info() прмиеняемый к объекту класса DataFrame показывает следующую информацию: 
- Сколько есть записей в таблице
- Какие колонки включены в таблицу
- Какой тип данных у записей в колонках
- Сколько информации занимает данная таблица

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41007 entries, 0 to 41006
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  41007 non-null  object
 1   Model                 41007 non-null  object
 2   Year                  41007 non-null  int64
 3   Style                 41007 non-null  object
 4   Distance              41007 non-null  float64
 5   Engine_capacity(cm3)  41007 non-null  float64
 6   Fuel_type             41007 non-null  object
 7   Transmission          41007 non-null  object
 8   Price(euro)           41007 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 2.8+ MB

Также есть команда для просмотра статистических данных

In [19]:
df.describe()

               Year      Distance  Engine_capacity(cm3)   Price(euro)
count  37264.000000  3.726400e+04          37264.000000  3.726400e+04
mean    2007.709264  4.758488e+05           1858.932535  9.569387e+03
std        8.295806  4.591520e+06            707.662731  5.283315e+04
min     1900.000000  0.000000e+00              0.000000  1.000000e+00
25%     2004.000000  9.000000e+04           1499.000000  3.300000e+03
50%     2009.000000  1.700000e+05           1800.000000  6.490000e+03
75%     2014.000000  2.300000e+05           2000.000000  1.179900e+04
max     2021.000000  1.000000e+08           9999.000000  1.000000e+07

Метод duplicate показывает дублирующиеся данные в наборе данных, sum прмиеняется для подсчёта этих дубликатов

In [15]:
print(df.duplicated().sum())

3743

В наборе данных почти 10% дубликатов, от них необходимо избавиться

Для этого будет применены методы drop_duplicates для удаления дубликатов и reset_index для того, чтобы пересчитать индексы в таблице

In [16]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)
df

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Transmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,Automatic,7750.0
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,Manual,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,Manual,2200.0
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,Manual,6550.0
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,Manual,4100.0
...,...,...,...,...,...,...,...,...,...
37259,Land Rover,Freelander,2002,Crossover,225000.0,1800.0,Metan/Propan,Manual,4400.0
37260,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,Manual,7000.0
37261,Renault,Modus,2009,Hatchback,225.0,1500.0,Diesel,Manual,4500.0
37262,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,Manual,4000.0
37263,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,Manual,4000.0

Для просмотра первых строк таблицы используется метод head(n), где n - число строк

In [17]:
df.head(10)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Transmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,Automatic,7750.0
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,Manual,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,Manual,2200.0
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,Manual,6550.0
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,Manual,4100.0
5,Mercedes,Vito,2000,Microvan,300000.0,2200.0,Diesel,Manual,3490.0
6,Volkswagen,Passat,2010,Universal,290000.0,1390.0,Petrol,Manual,5600.0
7,Volkswagen,Touareg,2010,SUV,220000.0,2400.0,Diesel,Automatic,17000.0
8,Mercedes,Series (W124),1991,Sedan,240000.0,2300.0,Petrol,Manual,2850.0
9,BMW,5 Series,2004,Sedan,325000.0,300.0,Diesel,Manual,3400.0

Для просмотра последних строк таблицы используется метод tail(n), где n - число строк

In [18]:
df.tail(10)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Transmission,Price(euro)
37254,Toyota,Avensis Verso,2004,Minivan,245627.0,2000.0,Diesel,Manual,7490.0
37255,Renault,Megane,2011,Sedan,145000.0,1500.0,Diesel,Automatic,6200.0
37256,Toyota,Auris,2007,Hatchback,222111.0,1400.0,Diesel,Automatic,4444.0
37257,Skoda,Superb,2016,Cabriolet,78900.0,2000.0,Petrol,Automatic,21000.0
37258,Volkswagen,Passat,2016,Sedan,88000.0,1800.0,Petrol,Automatic,11500.0
37259,Land Rover,Freelander,2002,Crossover,225000.0,1800.0,Metan/Propan,Manual,4400.0
37260,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,Manual,7000.0
37261,Renault,Modus,2009,Hatchback,225.0,1500.0,Diesel,Manual,4500.0
37262,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,Manual,4000.0
37263,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,Manual,4000.0

Для доступа к группе строк или столбцов по их обозначениям можно использовать атрибут loc

In [24]:
print(df.loc[0,'Year'])

2011

## Манипуляции с DataFrame

Для сортировки значений в DataFrame можно использовать метод .sort_values(by), в котором можно указать основание сортировки, порядок, игнорирование индексов и прочее

In [25]:
df.sort_values(by = 'Price(euro)', ascending=True).head(10)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Transmission,Price(euro)
18658,Opel,Frontera,1999,SUV,296.0,2200.0,Diesel,Automatic,1.0
19867,Mercedes,Series (W124),1989,Universal,1111.0,3000.0,Diesel,Automatic,1.0
5077,Audi,A6,2004,Universal,12345.0,2500.0,Diesel,Manual,1.0
14463,Alta marca,Alt model,1997,Crossover,1999922.0,1600.0,Petrol,Manual,5.0
14478,Alta marca,Alt model,1992,Sedan,192222.0,1300.0,Petrol,Manual,5.0
14547,Vaz,Altele,1989,Universal,199888.0,1300.0,Petrol,Manual,5.0
23072,Nissan,Primera,1991,Universal,60527210.0,2000.0,Petrol,Manual,10.0
14801,Volkswagen,Golf,1996,Hatchback,350653.0,1600.0,Metan/Propan,Manual,10.0
13886,Nissan,Sunny,1993,Universal,230000.0,2000.0,Diesel,Manual,100.0
21964,BMW,3 Series,1995,Sedan,200000.0,1600.0,Petrol,Manual,100.0

Сохранение DataFrame как отдельного csv файла возможн ос помощью метода to_csv()

In [26]:
df.to_csv('cars_nodup.csv', index=False)

# Контрольные вопросы

Вопрос: Назовите тип данных категориальных столбцов в Pandas

In [27]:
print(df.select_dtypes(include='object').dtypes)

Make            object
Model           object
Style           object
Fuel_type       object
Transmission    object
dtype: object

Вопрос: Назовите целевой столбец для задачи регрессии

In [30]:
df["Price(euro)"].head(10)

0     7750.0
1     8550.0
2     2200.0
3     6550.0
4     4100.0
5     3490.0
6     5600.0
7    17000.0
8     2850.0
9     3400.0
Name: Price(euro), dtype: float64

Вопрос: Назовите целевой столбец для задачи классификации

`Ответ: любой из категориальных, например стиль или тип кузова`

Вопрос: Возьмите датафрейм после удаления дубликатов. Выберете из полного датафрейма строки с индекса 69 по 322. Отсортируйте полученный датафрейм по колонке 'Distance' по убыванию. Какое значение колонки 'Style' у полученного датафрейма во второй строке сверху

In [31]:
df_selected = df.loc[69:322].sort_values(by='Distance', ascending=False)
print(df_selected.iloc[1]['Style'])

Minivan

Вопрос: Укажите правильную размерность исходного набора данных

In [33]:
df = pd.read_csv('archive/2cars_moldova.csv', delimiter = ',')
print(df.shape)

(41007, 9)